In [1]:
import json

In [13]:
j=json.load(open("../histograms_5-10_50nn/6-45.json"))

In [14]:
bins=j["distance_bins"]

In [15]:
len(bins[0])

27

In [16]:
# scoring bonus per pose, for each occurence of such a bead-bead distance in that pose
bins[1]

[[2.0, 3.054648400969203],
 [2.5, 3.054648400969203],
 [3.0, -0.48206558097531804],
 [3.5, -0.5334894833432013],
 [4.0, -0.553224339299855],
 [4.5, -0.8837918078865341],
 [5.0, -0.958541724726671],
 [5.5, -0.6853993397191331],
 [6.0, -0.4183527128219362],
 [6.5, -0.500699660520211],
 [7.0, -0.620853685532361],
 [7.5, -0.6617506764251102],
 [8.0, -0.7582513388314887],
 [8.5, -0.9318906566020058],
 [9.0, -0.6002651658946734],
 [9.5, -0.667020875967725],
 [10.0, -0.5888561031183883],
 [11.5, -0.44303401867040204],
 [13.0, -0.2892330918518349],
 [14.5, -0.43772521496554884],
 [16.0, -0.7795980217336824],
 [17.5, -1.0577639946628485],
 [19.0, -1.5623329459472322],
 [20.5, -2.0073813728713823],
 [22.0, -1.4012832631890078],
 [23.5, -1.028522860654773],
 [25.0, -1.1657448085594613],
 [999, -1.1060047227510426]]

In [17]:
import numpy as np

In [18]:
a = np.load("../distance-arrays/6-45.npy")

In [22]:
a.dtype

dtype([('distance_ranges', '<f4', (27,)), ('rank_ranges', '<u4', (3,)), ('data', '<u4', (3, 28, 2))])

In [24]:
a["distance_ranges"]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 11.5, 13. , 14.5, 16. , 17.5,
       19. , 20.5, 22. , 23.5, 25. ], dtype=float32)

In [25]:
# rank chunks
a["rank_ranges"]

array([16332, 32664, 33332], dtype=uint32)

In [36]:
#enrichment/depletion of that distance bin in NN(left) or in non-NN(right), compared to random distances 
aa=a['data'][0]
b=aa/aa.mean(axis=0)
b

array([[1.03247863, 0.48535038],
       [0.36923077, 0.26142995],
       [0.31452991, 0.32522454],
       [0.32820513, 0.38987162],
       [0.57435897, 0.42056122],
       [0.48547009, 0.46204902],
       [0.54017094, 0.50296849],
       [0.52649573, 0.55099203],
       [0.51965812, 0.56193231],
       [0.73846154, 0.62501649],
       [0.58803419, 0.67076673],
       [0.68376068, 0.69548891],
       [0.76581197, 0.67843913],
       [0.7042735 , 0.69861471],
       [0.76581197, 0.73598214],
       [0.80683761, 0.78684731],
       [0.92307692, 0.77164459],
       [3.30940171, 2.29234282],
       [3.06324786, 2.24787131],
       [2.2017094 , 1.91213274],
       [1.51111111, 1.56971634],
       [1.23076923, 1.45732988],
       [0.64957265, 1.27049272],
       [0.45128205, 1.07314152],
       [0.36239316, 0.89184554],
       [0.56068376, 0.73413508],
       [0.65641026, 0.65542193],
       [3.33675214, 4.27239052]])

In [37]:
#log odds
np.log(b[:,0]/b[:,1])

array([ 0.75484656,  0.34525547, -0.03343665, -0.1721787 ,  0.31166453,
        0.04944668,  0.07135812, -0.04547714, -0.07821026,  0.16679098,
       -0.13163635, -0.01700709,  0.1211419 ,  0.0080674 ,  0.03973081,
        0.0250882 ,  0.1791885 ,  0.36719306,  0.30949206,  0.14101482,
       -0.03804972, -0.16896655, -0.67084539, -0.86625309, -0.90056325,
       -0.269536  ,  0.00150679, -0.24717559])

In [31]:
#occurences of each distance bin (1 bin per line) in all NN (left) or all non-NN (right) poses
aa

array([[  151,  3416],
       [   54,  1840],
       [   46,  2289],
       [   48,  2744],
       [   84,  2960],
       [   71,  3252],
       [   79,  3540],
       [   77,  3878],
       [   76,  3955],
       [  108,  4399],
       [   86,  4721],
       [  100,  4895],
       [  112,  4775],
       [  103,  4917],
       [  112,  5180],
       [  118,  5538],
       [  135,  5431],
       [  484, 16134],
       [  448, 15821],
       [  322, 13458],
       [  221, 11048],
       [  180, 10257],
       [   95,  8942],
       [   66,  7553],
       [   53,  6277],
       [   82,  5167],
       [   96,  4613],
       [  488, 30070]], dtype=uint32)